language: node_js
node_js:
  - "7"
before_script: 
    - cd topicos/ambientacao/classe
    - npm install

- cd topicos/ambientacao/classe && npm install && npm run lint
# - cd ../../ambientacao/modulos && npm install && npm run test
