language: node_js
node_js:
  - "8"

addons:
  sonarcloud:
    organization: "kyriosdata-github"

before_script: 
    - cd topicos/ambientacao
    - npm install
script:
    - npm run lint
    - sonar-scanner
